# Generated by Django 2.1.5 on 2019-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20190415_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.DecimalField(decimal_places=10, max_digits=22, null=True),
        ),
    ]
